on:
  push:
    branches:
      - master

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Dependencies
        run: sudo apt-get install -y lib32stdc++6 lib32z1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Specify the Flutter version known to work with your project
          channel: 'stable'

      - name: Flutter Upgrade
        run: flutter upgrade

      - name: Install Android SDK Components
        run: sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi --verbose

      - name: List APKs
        run: ls -la build/app/outputs/apk/release/

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
